name = "link-shortener-backend"
main = "src/index.ts"
compatibility_date = "2025-01-29"
compatibility_flags = ["nodejs_compat"]
routes = [
  { pattern = "l.jfa.dev", custom_domain = true },
]

[observability]
enabled = true

[placement]
mode = "smart"

