name: Cloudflare Worker Pipeline

on:
  workflow_dispatch:
  push:
    paths:
      - "cloudflare/**"
    branches:
      - master
      - dev

jobs:
  deploy-cf-worker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "node"

      - name: Install Dependencies
        run: |
          cd cloudflare
          npm install
          npm install -g pnpm

      - name: Configure KV namespace
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        env:
          CF_KV_BINDING: ${{ secrets.CF_KV_BINDING }}
          CF_KV_ID: ${{ secrets.CF_KV_ID }}
        run: |
          cd cloudflare
          sed -i "s/<BINDING_NAME>/$CF_KV_BINDING/g" wrangler.toml
          sed -i "s/<NAMESPACE_ID>/$CF_KV_ID/g" wrangler.toml

      - name: Deploy to Cloudflare
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          cd cloudflare
          pnpx wrangler deploy
